In [1]:
import numpy as np #importing library numpy

import matplotlib.pyplot as plt  #importing plotting library; use this to make plots


Create the following matrix in Python and assign it to $x3$:


$$x_3 = 
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\ 
3 & 4 & 5 & 6 & 7
\end{bmatrix}$$

In [2]:
#enter code to make matrix here

x3 = [[1,2,3,4,5],[3,4,5,6,7]]


Determine the size of the matrix $x3$

In [3]:
np.shape(x3) 
#gives dimensions of x3

(2, 5)

If we use `np.size(x3)`, what result would we obtain?

In [4]:
# determine size of matrix x3 using numpy package

np.size(x3)

10

Run code 
`x1 = np.linspace(1,6,6)`
to generate a vector **x1**.

1. How many elements are in _x1_?
2. Write a code to access the first element in _x1_
3. Write a code to access the last element in _x1_.

Create a vector named _x1_

In [5]:
#create a vector named x1

x1= np.linspace(1,6,6) # creates a vector from 1 to 6 with 6 elements

#print vector 
print(x1)

[1. 2. 3. 4. 5. 6.]


Write a code to access the number of elements in _x1_

In [6]:
# number of elements in x1

print(len(x1))  # prints size of vector (number of elements)
print(np.size(x1)) # prints size of vector (number of elements)

6
6


Write a code to access the first element in _x1_

In [7]:
# access the first element in x1

print(x1[0]) # prints first element in x1

# NOTE: counting of arrays starts with 0!

1.0


In [8]:
# access last element in x1

print(x1[5]) # prints last element in x1

6.0


Given the vector $x$, extract all numbers satisfying condition $2 \leq x \leq 9$.

In [9]:
# create a vector x from 0 to 10 with 11 elements
x = np.linspace(0,10,11)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
x[2:10]

array([2., 3., 4., 5., 6., 7., 8., 9.])

For the above code,
- 2 states that we start at the second element on the list, don't forget that the slicing index starts at 0
- 10 states that we end at the 10th element in the list, but does not include it.
- The colon in the middle states that we want to use slicing to get objects in the list.

In [11]:
# What about the following code?
x[2:11]
# Starts at the second element (index starting at zero) 
# and ends at the 11th element, not inclusive.

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
# What about the following code?
x[1:11:2]
# Starts at the first element (index starting at zero)
# and ends at the 11th element, non inclusive
# elements go up by 2

array([1., 3., 5., 7., 9.])

In [13]:
# What about the following code?
x[::-1]
# Elements in x count backwards

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.])

Note that in the above:
- Since there is no value before the first colon, it will start at the beginning index of the list.
- Since tehre is no value after the first colon, it will go all the way to the end of the list.
- $-1$ makes the index to increment every time by $-1$, causing it to traverse the list by going backwards.

Given that `xnew = [1, 2, 3, 4]`, write a code to sum the numbers in `xnew`.

In [14]:
xnew = [1, 2, 3, 4] # create matrix xnew
sum1 = np.sum(xnew) # adds all elements in xnew
print(sum1) # prints value of sum1 to output

10


In [15]:
# you can also use the following code to sum
sum2 = sum(xnew) 
# adds all elements in xnew, without numpy package
print(sum2)  # prints to output

10


#### Example: Finding the slope of a line.

Given the equation $y = 5x$, plot the graph for $0 \leq x \leq 10$ and write a code to determine the slope.

In [16]:
# Enter your code here

# Construct linear space from 0 to 10 for x values
xval = np.linspace(0,10,11)
yval = 5*xval # Constructs an array with values of 5*x

# Calculate slope value
slope = (yval[1] - yval[0])/(xval[1] - yval[0])
print(slope) # Prints slope value to output

5.0


In [17]:
# Here is an alternative code for finding the slope
xval = np.linspace(0,10,11)
yval = 5*xval

nvals = xval.size # Assigns varible with size of array

# Construct an array with slope values using slope formula
slopes = (yval[1:nvals] - yval[0:nvals-1])/(xval[1:nvals] - xval[0:nvals-1])

print(np.min(slopes)) # Prints minimum value in array 'slopes'
print(np.max(slopes)) # Prints maximum value in array 'slopes'
print(np.mean(slopes)) # Prints mean value (average) of array 'slopes'

print(slopes)



5.0
5.0
5.0
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
